# assetsディレクトリをdevelop/assetsにAlias
Alias /assets /var/www/html/develop/assets

<Directory "/var/www/html/develop/assets">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>
